stages:
  - build

build-apk:
  stage: build
  image: kivy/buildozer:latest
  tags:
    - docker
  before_script:
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
  script:
    - buildozer android debug
  artifacts:
    name: "gxy-apk-$CI_COMMIT_SHORT_SHA"
    paths:
      - bin/*.apk
    expire_in: 30 days
  only:
    - main
    - master
